//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SUNCLOCK.RC
//
#define IDS_ERR_REGISTER_CLASS          1
#define IDS_ERR_CREATE_WINDOW           2
#define IDS_ERR_IERR                    4
#define IDS_ERR_MEMOBJCAT               7
#define IDS_ERR_SATELEM                 9
#define IDS_DAY_NAMES                   16
#define IDS_MONTH_NAMES                 48
#define IDS_MINUTE                      96
#define IDS_MINUTES                     97
#define IDS_HOUR                        98
#define IDS_HOURS                       99
#define IDS_DAY                         100
#define IDM_S_CONALIGN                  101
#define DLG_RELATED                     101
#define IDS_DAYS                        101
#define IDM_S_HORIZON                   102
#define IDS_NONE                        102
#define IDS_APPNAME                     103
#define IDR_SETTINGS1                   103
#define IDM_F_VFOBSLOC                  104
#define IDS_HELPFILE                    104
#define IDS_HELPHELP                    105
#define IDS_IMAGE_DIRECTORY             106
#define IDS_ALIAS_FILENAME              107
#define IDS_OBJCAT_FILENAME             108
#define IDS_CONLINE_FILENAME            109
#define IDS_SAT_DEFDB                   110
#define IDS_SAT_FILTER                  111
#define IDS_SAT_TITLE                   112
#define IDS_HELP_ON_UTC                 120
#define IDS_HELP_ON_JDATE               121
#define IDS_HELP_ON_SATICON             122
#define IDS_HELP_ON_SATRACK             123
#define IDS_HELP_ON_SATDBASE            124
#define IDS_HELP_ON_SUNMOON             125
#define IDS_HELP_ON_SATVIEW             126
#define IDS_HELP_ON_TIMEZONE            127
#define IDS_HELP_ON_PLANETS             128
#define IDS_HELP_ON_OBSLOC              129
#define IDS_HELP_ON_SKY                 130
#define IDS_HELP_ON_SCOPE               131
#define IDS_HELP_ON_OBJCAT              132
#define IDS_HELP_ON_ORRERY              133
#define IDS_HELP_ON_TELOPTS             134
#define IDS_HELP_ON_HORIZON             135
#define IDS_HELP_ON_HOROPTS             136
#define IDS_UP                          150
#define IDS_SET                         151
#define IDS_RISING                      152
#define IDS_SETTING                     153
#define IDS_NORTH                       154
#define IDS_SOUTH                       155
#define IDS_EAST                        156
#define IDS_WEST                        157
#define IDS_TRANSIT                     158
#define IDS_NEED_SITENAME               159
#define IDS_CONBOUND_FILENAME           160
#define IDS_CNAMES_FILENAME             161
#define IDS_GREEK_FONTNAME              162
#define IDS_DEEP_CODES                  163
#define IDS_DEEP_FILENAME               164
#define IDS_OC_RA                       165
#define IDS_OC_DEC                      166
#define IDS_OC_IMAGE                    167
#define IDS_OC_SOUND                    168
#define IDS_SOUND_DIRECTORY             169
#define IDS_IMAGE_DEFAULT               170
#define idsInsuffSkyMemory              171
#define idsInsuffTelMemory              172
#define idsInsuffHorMemory              173
#define IDS_OC_TYPE                     174
#define IDS_OC_LABEL                    175
#define IDS_STARMAPLIB                  176
#define IDS_REGISTRY_SECTION			177
#define IDS_FORMATS                     200
#define IDS_CARDINAL_POINTS             300
#define IDS_CARDINAL_ABBR               320
#define IDM_F_IMAGE                     700
#define IDM_F_IMAGE_POP                 799
#define IDC_HO_CARDINAL                 1000
#define IDM_FILE                        1000
#define IDC_HO_DEGREES                  1001
#define IDC_HO_FOV                      1002
#define IDC_HO_LIMAG                    1003
#define IDC_HO_OPTIONS                  1004
#define IDC_HO_HELP                     1005
#define IDC_HO_HSCROLL                  1006
#define IDC_HO_PANEL                    1007
#define IDC_HO_TERRHOR                  1008
#define IDC_HO_TERROUGH                 1009
#define IDC_OC_PLOT                     1010
#define IDC_HO_SCENERY                  1011
#define IDC_TO_MAXMAG                   1011
#define IDC_TO_MINMAG                   1012
#define IDM_F_EXIT                      1050
#define IDM_F_SAVESETTINGS              1060
#define IDM_F_DEFSETTINGS               1070
#define IDR_PLANETS                     1700
#define IDR_SUN                         1700
#define IDR_MERCURY                     1701
#define IDR_VENUS                       1702
#define IDR_EARTH                       1703
#define IDR_MARS                        1704
#define IDR_JUPITER                     1705
#define IDR_SATURN                      1706
#define IDR_URANUS                      1707
#define IDR_NEPTUNE                     1708
#define IDR_PLUTO                       1709
#define IDR_ASTEROID                    1710
#define IDR_COMET                       1711
#define IDR_STARS                       1751
#define IDR_STAR1                       1751
#define IDR_STAR2                       1752
#define IDR_STAR3                       1753
#define IDR_STAR4                       1754
#define IDR_STAR5                       1755
#define IDR_STAR6                       1756
#define IDR_STAR7                       1757
#define IDR_STAR8                       1758
#define IDR_STAR9                       1759
#define IDR_DEEP                        1781
#define IDR_DEEPEG                      1781
#define IDR_DEEPSG                      1782
#define IDR_DEEPOC                      1783
#define IDR_DEEPGC                      1784
#define IDR_DEEPDN                      1785
#define IDR_DEEPPN                      1786
#define IDR_DEEPQS                      1787
#define IDR_DEEPDS                      1788
#define IDR_DEEPDK                      1789
#define IDR_DEEPIG                      1790
#define IDM_EDIT                        2000
#define IDM_S_SCOPE                     2001
#define IDM_S_CONSTELL                  2002
#define IDM_S_CONBOUNDS                 2003
#define IDM_S_CONNAMES                  2004
#define IDM_S_STARNAMES                 2005
#define IDM_S_BFLAM                     2006
#define IDM_S_DEEPSKY                   2007
#define IDM_S_COORDS                    2008
#define IDM_S_PLANETS                   2009
#define IDM_F_COPY                      2050
#define IDM_S_STARSLOW                  2150
#define IDM_S_STARSMED                  2151
#define IDM_S_STARSHIGH                 2152
#define IDM_S_STARCOL                   2160
#define IDM_S_YALE                      2200
#define IDM_S_SAO                       2201
#define IDM_S_HUBBLE                    2202
#define IDM_S_PREC                      2300
#define IDM_OPTIONS                     3000
#define IDM_F_TESTMODE                  3050
#define IDM_F_STOP                      3060
#define IDM_F_RUN                       3070
#define IDM_F_SETJDATE                  3080
#define IDM_F_SETUTIME                  3090
#define IDM_F_SETOBSLOC                 3092
#define IDM_F_CUCKOO                    3095
#define IDM_F_DISPMONO                  3100
#define IDM_F_DISPC16                   3110
#define IDM_F_DISPC256                  3120
#define IDM_F_DISPGREY                  3130
#define IDC_TELESCOPE                   3200
#define IDC_TE_PANEL                    3201
#define IDC_TE_HELP                     3202
#define IDC_TE_VSCROLL                  3203
#define IDC_TE_HSCROLL                  3204
#define IDC_TE_RA                       3207
#define IDC_TE_DEC                      3209
#define IDC_TE_POWER                    3212
#define IDC_TE_FOV                      3215
#define IDC_TE_LIMAG                    3216
#define IDC_TE_OPTIONS                  3217
#define IDM_F_SUNMOON                   3230
#define IDM_F_SHOWMOON                  3240
#define IDM_F_PLANPAN                   3242
#define IDM_F_OBJCAT                    3243
#define IDM_F_SKY                       3245
#define IDM_F_ORRERY                    3248
#define IDM_F_SATVIEW1                  3250
#define IDM_F_DAYVIEW                   3251
#define IDM_F_MOONVIEW                  3252
#define IDM_F_NIGHTVIEW                 3253
#define IDM_F_TEXTUREVIEW               3254
#define IDM_F_VECTORVIEW                3255
#define IDM_F_ANIMIN                    3300
#define IDM_F_ANIHOUR                   3301
#define IDM_F_ANIDAY                    3302
#define IDM_F_ANIWEEK                   3303
#define IDM_F_ANIMONTH                  3304
#define IDM_F_ANIYEAR                   3305
#define IDM_F_ANISDAY                   3306
#define IDM_F_ANISYEAR                  3307
#define IDM_F_ANIDECADE                 3308
#define IDM_F_ANICENTURY                3309
#define IDM_F_ANIMILL                   3310
#define IDM_F_ANIFWD                    3318
#define IDM_F_ANIBACK                   3319
#define IDM_F_ANISFAST                  3320
#define IDM_F_ANISMED                   3321
#define IDM_F_ANISSLOW                  3322
#define IDC_OBSLOC                      3400
#define IDM_OBSLOC                      3400
#define IDM_OL_HELP                     3401
#define IDM_OL_LATDEG                   3402
#define IDM_OL_LATMIN                   3403
#define IDM_OL_LATSEC                   3404
#define IDM_OL_SITENAME                 3405
#define IDM_OL_LONDEG                   3406
#define IDM_OL_LONMIN                   3407
#define IDM_OL_LONSEC                   3408
#define IDM_OL_NORS                     3418
#define IDM_OL_EORW                     3419
#define IDM_OL_PICK                     3420
#define IDM_OL_CLOSECITY                3421
#define IDC_ABOUT                       3500
#define IDC_AB_USER                     3507
#define IDM_F_SATTRACK                  3510
#define IDC_AB_ORG                      3512
#define IDM_F_SATDBASE                  3530
#define IDM_F_SATICON                   3540
#define IDC_SATICON                     3800
#define IDC_SI_BUTTONS                  3801
#define IDC_SI_ICONS                    3900
#define IDC_ORRERY                      3900
#define IDC_OR_IMAGE                    3901
#define IDC_OR_HELP                     3902
#define IDC_OR_VSCROLL                  3903
#define IDC_OR_HSCROLL                  3904
#define IDC_OR_ALLPLAN                  3906
#define IDC_OR_INNER                    3907
#define IDC_OR_LONG                     3910
#define IDC_OR_LAT                      3912
#define IDC_OR_REAL                     3914
#define IDC_OR_LOG                      3915
#define IDC_OR_SCHEMA                   3916
#define IDC_OR_EQUAL                    3917
#define IDC_SI_HELP                     3920
#define IDM_HELP                        4000
#define IDM_F_HELPCONT                  4020
#define IDM_F_HELPHOW                   4030
#define IDM_F_HELPSEARCH                4040
#define IDM_F_ABOUT                     4050
#define IDC_SATVIEW                     5300
#define IDC_SV_HELP                     5301
#define IDC_SV_IMAGE                    5302
#define IDC_SV_POSITION                 5303
#define IDC_SV_SHOWTERM                 5304
#define IDC_TELOPTS                     5400
#define IDC_TO_HELP                     5401
#define IDC_TO_CONOUTL                  5403
#define IDC_TO_CONBOUND                 5404
#define IDC_TO_CONNAMES                 5405
#define IDC_TO_SOUTHUP                  5407
#define IDC_TO_SHOWDEEP                 5410
#define IDC_TO_SHOWNAME                 5411
#define IDC_TO_NAMEMAGL                 5413
#define IDC_TO_SHOWBFLAM                5415
#define IDC_TO_BFLAMAG                  5417
#define IDC_TO_DEEPMAG                  5419
#define IDC_TO_COORDS                   5420
#define IDC_TO_SSOBJ                    5421
#define IDC_TO_SHOWMAG                  5423
#define IDC_SETUTIME                    6000
#define IDC_U_YEAR                      6001
#define IDC_U_MONTH                     6003
#define IDC_U_DAY                       6004
#define IDC_U_HOUR                      6005
#define IDC_U_MINUTE                    6006
#define IDC_U_SECOND                    6007
#define IDC_U_NOW                       6015
#define IDC_U_JDATE                     6016
#define IDC_U_HELP                      6017
#define IDM_PL_RA                       6600
#define IDM_PL_DEC                      6620
#define IDM_PL_DIST                     6640
#define IDM_PL_ALT                      6660
#define IDM_PL_AZ                       6680
#define IDM_PLANPOS                     6700
#define IDC_PLANPOS                     6700
#define IDM_PL_HELP                     6715
#define IDM_PL_PLUTO                    6716
#define IDM_PL_ASTEROID                 6717
#define IDM_PL_UPSET                    6750
#define SMI_JD                          6801
#define SMI_UT                          6802
#define SMI_LT                          6803
#define SMI_AOM                         6804
#define SMI_PHASE                       6805
#define SMI_MDIST                       6806
#define SMI_MSUBT                       6807
#define SMI_SDIST                       6808
#define SMI_SSUBT                       6809
#define SMI_PH1                         6810
#define SMI_PH2                         6811
#define SMI_PH3                         6812
#define SMI_PH4                         6813
#define SMI_PH5                         6814
#define SMI_LU1                         6820
#define SMI_LU2                         6821
#define SMI_MOON                        6825
#define SMI_LTL                         6830
#define SMI_HELP                        6840
#define IDC_SATTRACK                    7000
#define IDC_OBJCAT                      7100
#define IDC_OC_OBJNAME                  7101
#define IDC_OC_IMAGE                    7104
#define IDC_OC_DBINFO                   7105
#define IDC_OC_CATEGORY                 7106
#define IDC_OC_HELP                     7107
#define IDC_OC_AIM                      7116
#define IDC_OC_CAPTIONS                 7120
#define IDC_SUNMOON                     7500
#define IDC_JDATE                       9000
#define IDC_HORIZON                     9001
#define IDC_J_UTIME                     9001
#define IDC_HOROPTS                     9002
#define IDC_J_NOW                       9003
#define IDC_J_HELP                      9004
#define IDC_J_JDATE                     9005
#define ST_SAT                          9901
#define ST_LYEAR                        9902
#define ST_LNO                          9903
#define ST_PIECE                        9904
#define ST_INC                          9905
#define ST_ECCENT                       9906
#define ST_REVDAY                       9907
#define ST_LAT                          9908
#define ST_LON                          9909
#define ST_ALT                          9910
#define ST_ORBNO                        9911
#define ST_ECLIPSE                      9912
#define ST_C_HELP                       9920
#define ST_C_TRACK                      9921
#define ST_LIST                         9980
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         106
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
